import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    paddingBottom: 40, // espaço extra para safe area
  },
  title: {
    fontSize: 26,
    marginBottom: 20,
    fontWeight: '600',
    color: '#333',
  },
  pickerBox: {
    backgroundColor: 'rgba(255,255,255,0.85)',
    borderRadius: 18,
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderWidth: 0,
    marginBottom: 24,
    width: '100%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  label: {
    marginBottom: 6,
    fontSize: 16,
    fontWeight: '500',
  },
  input: {
    fontSize: 17,
    paddingVertical: 14,
    paddingHorizontal: 14,
    color: '#222',
    backgroundColor: 'rgba(245,245,245,0.85)',
    borderRadius: 12,
    marginTop: 4,
    borderWidth: 0,
  },
  spinButton: {
    backgroundColor: 'rgba(255,255,255,0.18)',
    paddingVertical: 16,
    paddingHorizontal: 48,
    borderRadius: 32,
    marginBottom: 10,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.45)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.10,
    shadowRadius: 18,
    elevation: 6,
    backdropFilter: 'blur(12px)', // para web, ignorado no mobile
  },
  spinText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: 1.2,
    textShadowColor: 'rgba(0,0,0,0.18)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 8,
  },
  slotContainerModern: {
    backgroundColor: 'rgba(255,255,255,0.65)',
    borderRadius: 32,
    paddingVertical: 24,
    paddingHorizontal: 32,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 180,
    marginVertical: 18,
    borderWidth: 0,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.10,
    shadowRadius: 24,
    elevation: 8,
    backdropFilter: 'blur(12px)', // para web, ignorado no mobile
  },
  clearButton: {
    marginTop: 24,
    marginBottom: 24, // espaço extra para não ficar escondido
    backgroundColor: 'rgba(245,245,245,0.85)',
    paddingVertical: 13,
    paddingHorizontal: 44,
    borderRadius: 32,
    alignItems: 'center',
    borderWidth: 0,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 1,
  },
  clearText: {
    color: '#222',
    fontSize: 16,
    fontWeight: '600',
    letterSpacing: 1.1,
  },
  resultBox: {
    alignItems: 'flex-start',
    padding: 24,
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderRadius: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
    width: '92%',
    marginTop: 10,
  },
  resultName: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#222',
    marginBottom: 12,
  },
  resultRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    flexWrap: 'wrap',
  },
  resultLabel: {
    fontWeight: 'bold',
    color: '#222',
    fontSize: 16,
    marginRight: 6,
  },
  resultValue: {
    color: '#444',
    fontSize: 16,
    flexShrink: 1,
  },
  resultLinkButton: {
    marginTop: 10,
    backgroundColor: '#3478F6',
    borderRadius: 18,
    paddingVertical: 8,
    paddingHorizontal: 18,
    alignSelf: 'flex-start',
    minHeight: 44,
    justifyContent: 'center',
  },
  fullWidthButton: {
    width: '100%',
    alignSelf: 'stretch',
    alignItems: 'center',
    marginTop: 8,
    backgroundColor: '#2ecc71',
    borderRadius: 18,
    paddingVertical: 12,
    minHeight: 44,
    justifyContent: 'center',
  },
  link: {
    fontSize: 16,
    color: '#fff', // texto branco para contraste
    fontWeight: '600',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.3)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 20,
    width: '80%',
    maxHeight: '60%',
    alignItems: 'stretch',
  },
  modalItem: {
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    alignItems: 'center',
  },
  modalClose: {
    marginTop: 10,
    alignItems: 'center',
  },
  wheelOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  slotContainer: {
    backgroundColor: '#fff',
    borderRadius: 24,
    paddingVertical: 32,
    paddingHorizontal: 36,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 240,
    marginVertical: 24,
    borderWidth: 3,
    borderColor: '#4E9F3D',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 16,
    elevation: 12,
  },
  gradientBg: {
    flex: 1,
  },
  slotCircle: {
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: 'rgba(255,255,255,0.25)',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 24,
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.45)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.10,
    shadowRadius: 24,
    elevation: 8,
    backdropFilter: 'blur(12px)',
  },
  slotImage: {
    width: 80,
    height: 80,
    borderRadius: 40,
  },
  slotText: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#222',
    textAlign: 'center',
  },
  filterRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
    marginTop: 4,
    paddingHorizontal: 4,
  },
  filtersBlock: {
    width: '100%',
    marginBottom: 18,
  },
});

export default styles;
